version: '3.8'

services:
  dbb-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./dbb-server
    ports:
      - "8080:8082"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - tmp_dbb:/var/lib/postgresql/data
    ports:
      - "7890:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVER_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${SERVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}
      POSTGRES_DB: ${SERVER_DB_NAME}

volumes:
  tmp_dbb: