version: '3.8'

services:
  dbb-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./dbb-server
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}


  db:
    restart: always
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - /tmp:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVER_DB_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}