version: '3.8'

services:
  dbb-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbb-server
    restart: unless-stopped
    depends_on:
      - dbb-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - "${BIND_ADDR}:${BIND_ADDR}"
    networks:
      - appnet

  dbb-db:
    image: postgres:alpine3.20
    container_name: dbb-db
    restart: unless-stopped
    volumes:
      - ${SERVER_DB_VOLUME}:/var/lib/postgresql/data
    expose:
      - "${SERVER_DB_PORT}"
    ports:
      - "${SERVER_DB_PORT}:${SERVER_DB_PORT}"
    command: -p ${SERVER_DB_PORT}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${SERVER_DB_USERNAME}", "-d", "${SERVER_DB_NAME}", "-p", "${SERVER_DB_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      POSTGRES_USER: ${SERVER_DB_USERNAME}
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}
      POSTGRES_DB: ${SERVER_DB_NAME}
    networks:
      - appnet

volumes:
  tmp_dbb:

networks:
  appnet:
    name: appnet
    driver: bridge
