version: '3.8'

services:
  dbb-server:
    build: ./
    command: ./dbb-server
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      SERVER_DB_PASSWORD: ${SERVER_DB_PASSWORD}


  db:
    restart: always
    image: postgres:latest
    volumes:
      - /tmp:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_PASSWORD: ${SERVER_DB_PASSWORD}